spring.application.name=cashflow

# PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d4q46aa4i8rc73fjn4pg-a.oregon-postgres.render.com:5432/cashflow_3dl7?sslmode=require
spring.datasource.username=cashflow_3dl7_user
spring.datasource.password=i4OH0wTuQ1fyu4mK3E2NlEKzGdNxk65R
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Kein SQL-Autoload
spring.sql.init.mode=never
