# Name der Anwendung
spring.application.name=cashflow

# Datenbankverbindung zu PostgreSQL auf Render
spring.datasource.url=jdbc:postgresql://dpg-d4q46aa4i8rc73fjn4pg-a.oregon-postgres.render.com:5432/cashflow_3dl7?sslmode=require
spring.datasource.username=cashflow_3dl7_user
spring.datasource.password=i4OH0wTuQ1fyu4mK3E2NlEKzGdNxk65R
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate-Konfiguration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false  

# Verhindert die automatische SQL-Skriptausführung beim Start
spring.sql.init.mode=never


spring.jpa.properties.hibernate.hbm2ddl.auto=update

